#!/usr/bin/perl

use strict;
use warnings;

if($#ARGV!=0) { &syntax; }
my $ID=$ARGV[0];
# print "DEBUG: ARGV is $IP\n";

open(DEVICES,"<bertha.devices") || die "bertha.devices: $!\n\n";

my $found=0;

while(<DEVICES>)
{
 chop;
 my ($id,$name)=split(':');
 if($id=~/$ID/)
 {
  print "$name\n";
  $found=1;
  last;
 }
}

close(DEVICES);

if(not $found) { print "$ID\n"; }

exit(0);

sub syntax
{
 print "ERROR: No argument found in $#ARGV arguments.\n";
 print "  SYNTAX: $0 device_id\n";
 exit(1);
}
